import { Component } from "@angular/core";
import { FirestoreService, Tile } from "../../services/firestore.service";

@Component({
  selector: "app-tile-uploader",
  templateUrl: "./tile-uploader.component.html",
})
export class TileUploaderComponent {
  constructor(private firestoreService: FirestoreService) {}

  tiles: Tile[] = [
    {
      id: "tile11",
      name: "Falicsempe CALVANO GREY 25 cm x 40 cm x 0,8 cm",
      pricePerSqm: 3989,
      colorShade: "Szürke",
      surface: "Matt",
      material: "Kerámia",
      recommendedUse: "Beltér",
      width_cm: 25,
      depth_cm: 40,
      thickness_cm: 0.8,
      weight_kg: 18.5,
      imageUrl: "calvano-grey.jpg",
      stock: 100,
      location: "raktár E2",
    },
    {
      id: "tile12",
      name: "Falicsempe LAVENO WHITE 25 cm x 40 cm x 0,8 cm",
      pricePerSqm: 3890,
      colorShade: "Fehér",
      surface: "Fényes",
      material: "Kerámia",
      recommendedUse: "Beltér",
      width_cm: 25,
      depth_cm: 40,
      thickness_cm: 0.8,
      weight_kg: 18.2,
      imageUrl: "laveno-white.jpg",
      stock: 120,
      location: "raktár A2",
    },
    {
      id: "tile13",
      name: "Padlólap TORINO BEIGE 30 cm x 60 cm x 0,9 cm",
      pricePerSqm: 4290,
      colorShade: "Bézs",
      surface: "Matt",
      material: "Gres",
      recommendedUse: "Beltér",
      width_cm: 30,
      depth_cm: 60,
      thickness_cm: 0.9,
      weight_kg: 21.0,
      imageUrl: "torino-beige.jpg",
      stock: 90,
      location: "raktár B4",
    },
    {
      id: "tile14",
      name: "Falicsempe URBAN BLACK 25 cm x 40 cm x 0,8 cm",
      pricePerSqm: 4120,
      colorShade: "Fekete",
      surface: "Fényes",
      material: "Kerámia",
      recommendedUse: "Beltér",
      width_cm: 25,
      depth_cm: 40,
      thickness_cm: 0.8,
      weight_kg: 18.6,
      imageUrl: "urban-black.jpg",
      stock: 75,
      location: "raktár D3",
    },
    {
      id: "tile15",
      name: "Padlólap MARMO GREY 60 cm x 60 cm x 1 cm",
      pricePerSqm: 5290,
      colorShade: "Világosszürke",
      surface: "Fényes",
      material: "Porcelán",
      recommendedUse: "Beltér",
      width_cm: 60,
      depth_cm: 60,
      thickness_cm: 1.0,
      weight_kg: 25.4,
      imageUrl: "marmo-grey.jpg",
      stock: 60,
      location: "raktár F1",
    },
    {
      id: "tile16",
      name: "Falicsempe VINTAGE BLUE 20 cm x 20 cm x 0,7 cm",
      pricePerSqm: 4790,
      colorShade: "Kék",
      surface: "Matt",
      material: "Kerámia",
      recommendedUse: "Beltér",
      width_cm: 20,
      depth_cm: 20,
      thickness_cm: 0.7,
      weight_kg: 16.8,
      imageUrl: "vintage-blue.jpg",
      stock: 110,
      location: "raktár C3",
    },
    {
      id: "tile17",
      name: "Padlólap STONE EFFECT 30 cm x 60 cm x 0,9 cm",
      pricePerSqm: 4890,
      colorShade: "Sötétszürke",
      surface: "Strukturált",
      material: "Gres",
      recommendedUse: "Beltér és kültér",
      width_cm: 30,
      depth_cm: 60,
      thickness_cm: 0.9,
      weight_kg: 22.1,
      imageUrl: "stone-effect.jpg",
      stock: 85,
      location: "raktár E1",
    },
    {
      id: "tile18",
      name: "Dekorcsempe FLORAL WHITE 25 cm x 40 cm x 0,8 cm",
      pricePerSqm: 5290,
      colorShade: "Fehér mintás",
      surface: "Fényes",
      material: "Kerámia",
      recommendedUse: "Beltér",
      width_cm: 25,
      depth_cm: 40,
      thickness_cm: 0.8,
      weight_kg: 18.4,
      imageUrl: "floral-white.jpg",
      stock: 50,
      location: "raktár G2",
    },
    {
      id: "tile19",
      name: "Padlólap WOOD LOOK NATURAL 20 cm x 90 cm x 1 cm",
      pricePerSqm: 4990,
      colorShade: "Természetes fa",
      surface: "Matt",
      material: "Porcelán",
      recommendedUse: "Beltér",
      width_cm: 20,
      depth_cm: 90,
      thickness_cm: 1.0,
      weight_kg: 23.5,
      imageUrl: "wood-look.jpg",
      stock: 70,
      location: "raktár H1",
    },
    {
      id: "tile20",
      name: "Mozaikcsempe HEXA BLACK-WHITE 30 cm x 30 cm x 0,6 cm",
      pricePerSqm: 6290,
      colorShade: "Fekete-fehér",
      surface: "Fényes",
      material: "Kerámia",
      recommendedUse: "Beltér",
      width_cm: 30,
      depth_cm: 30,
      thickness_cm: 0.6,
      weight_kg: 17.9,
      imageUrl: "hexa-mosaic.jpg",
      stock: 55,
      location: "raktár G4",
    },
  ];

  uploadTiles() {
    this.firestoreService
      .bulkAddTiles(this.tiles)
      .then(() => {
        console.log("✅ Csempék sikeresen feltöltve!");
      })
      .catch((err) => {
        console.error("❌ Hiba történt a feltöltés során:", err);
      });
  }
}
